//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GIO_HANG
    {
        public string MAGH { get; set; }
        public string MASP { get; set; }
        public string MAMAU { get; set; }
        public string MASIZE { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual CHI_TIET_SP CHI_TIET_SP { get; set; }
        public virtual GIO_HANG GIO_HANG { get; set; }
    }
}
