//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEU_NHAP
    {
        public string MAPN { get; set; }
        public string MASP { get; set; }
        public string MAMAU { get; set; }
        public string MASIZE { get; set; }
        public string MACTPN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> DONGIANHAP { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual CHI_TIET_SP CHI_TIET_SP { get; set; }
        public virtual PHIEU_NHAP PHIEU_NHAP { get; set; }
    }
}
