//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH_SP
    {
        public string MAHINH { get; set; }
        public string MASP { get; set; }
        public string TENHINHANH { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
