//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHI_TIET_SP()
        {
            this.CT_DON_HANG = new HashSet<CT_DON_HANG>();
            this.CT_PHIEU_NHAP = new HashSet<CT_PHIEU_NHAP>();
        }
    
        public string MASP { get; set; }
        public string MAMAU { get; set; }
        public string MASIZE { get; set; }
        public string MACTSP { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual MAU_SAC MAU_SAC { get; set; }
        public virtual KICH_THUOC KICH_THUOC { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DON_HANG> CT_DON_HANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_NHAP> CT_PHIEU_NHAP { get; set; }
    }
}
