//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_HANG()
        {
            this.CT_DON_HANG = new HashSet<CT_DON_HANG>();
        }
    
        public string MADH { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public string HINHTHUCTHANHTOAN { get; set; }
        public string DIACHIGIAO { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
        public Nullable<int> TONGSOLUONG { get; set; }
        public Nullable<decimal> TONGTHANHTIEN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DON_HANG> CT_DON_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
