//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIO_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIO_HANG()
        {
            this.CT_GIO_HANG = new HashSet<CT_GIO_HANG>();
        }
    
        public string MAGH { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GIO_HANG> CT_GIO_HANG { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
